"""
Django settings for nexora_backend project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta
from dotenv import load_dotenv
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "django-insecure-default-key-replace-me")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG", "False") == "True"

ALLOWED_HOSTS = os.getenv("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")

# CORS settings
CORS_ALLOW_ALL_ORIGINS = os.getenv("DJANGO_CORS_ALLOW_ALL_ORIGINS", "False") == "True"
CORS_ALLOWED_ORIGINS = os.getenv("DJANGO_CORS_ALLOWED_ORIGINS", "http://localhost:3000,http://127.0.0.1:3000,http://localhost:5000,http://127.0.0.1:5000").split(",")


# Application definition

INSTALLED_APPS = [
    "unfold",  # Unfold birinchi turishi shart
    "unfold.contrib.filters",
    "unfold.contrib.forms",
    "unfold.contrib.import_export",
    "unfold.contrib.guardian",
    "unfold.contrib.simple_history",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "rest_framework",
    "corsheaders",
    "core",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',  # Tarjima uchun muhim
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
]

ROOT_URLCONF = 'nexora_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticatedOrReadOnly",
    ),
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=7),
    "AUTH_HEADER_TYPES": ("Bearer",),
}

WSGI_APPLICATION = 'nexora_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'uz'

TIME_ZONE = 'Asia/Tashkent'

USE_I18N = True

USE_TZ = True

LANGUAGES = [
    ('uz', 'Uzbek'),
    ('en', 'English'),
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# === Fly.io override: admin & API uchun aniq hostlar ===
# ALLOWED_HOSTS = ['*'] # Removed for security

CSRF_TRUSTED_ORIGINS = os.getenv("DJANGO_CSRF_TRUSTED_ORIGINS", "http://localhost:3000,http://127.0.0.1:3000,http://localhost:5000,http://127.0.0.1:9000").split(",")

UNFOLD = {
    "SITE_TITLE": "Nexora Admin",
    "SITE_HEADER": "Nexora Premium Admin",
    "INDEX_TITLE": "Boshqaruv paneliga xush kelibsiz",
    "SITE_URL": "/",
    "SITE_SYMBOL": "school",
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    "COLORS": {
        "primary": {
            "50": "238 242 255",
            "100": "224 231 255",
            "200": "199 210 254",
            "300": "165 180 252",
            "400": "129 140 248",
            "500": "99 102 241",
            "600": "79 70 229",
            "700": "67 56 202",
            "800": "55 48 163",
            "900": "49 46 129",
            "950": "30 27 75",
        },
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,
        "navigation": [
            {
                "title": "Asosiy",
                "items": [
                    {
                        "title": "Bosh sahifa",
                        "icon": "home",
                        "link": "/admin/",
                    },
                    {
                        "title": "Admin AI Assistant",
                        "icon": "smart_toy",
                        "link": "/admin/ai-assistant/",
                        "permission": "core.callbacks.is_superuser",
                    },
                ],
            },
             {
                "title": "Faollik va Reyting",
                "separator": True,
                "items": [
                    {
                        "title": "Ijtimoiy faollik",
                        "icon": "star",
                        "link": "/admin/core/socialachievement/",
                        "models": ["core.socialachievement"],
                        "badge": "core.callbacks.get_pending_social_count",
                    },
                    {
                        "title": "Reyting shakllantirish",
                        "icon": "settings",
                        "link": "/admin/core/academicyear/",
                        "models": ["core.academicyear"],
                        "permission": "core.callbacks.is_not_tutor",
                    },
                    {
                        "title": "Grant uchun nomzodlar",
                        "icon": "workspace_premium",
                        "link": "/admin/core/annualranking/",
                        "models": ["core.annualranking"],
                        "permission": "core.callbacks.is_not_tutor",
                    },
                ],
            },
            {
                "title": "Stipendiyalar",
                "separator": True,
                "items": [
                    {
                        "title": "Stipendiyalar",
                        "icon": "payments",
                        "link": "/admin/core/scholarship/",
                        "models": ["core.scholarship"],
                        "permission": "core.callbacks.is_not_tutor",
                    },
                    {
                        "title": "Stipendiya uchun hujjatlar",
                        "icon": "folder_shared",
                        "link": "/admin/core/studentdocument/",
                        "models": ["core.studentdocument"],
                        "badge": "core.callbacks.get_pending_document_count",
                    },
                    {
                        "title": "Stipendiya arizalari",
                        "icon": "assignment",
                        "link": "/admin/core/scholarshipapplication/",
                        "models": ["core.scholarshipapplication"],
                        "badge": "core.callbacks.get_pending_application_count",
                    },
                ],
            },
            {
                "title": "Talabalar",
                "separator": True,
                "items": [
                    {
                        "title": "Talabalar",
                        "icon": "people",
                        "link": "/admin/core/profile/",
                        "models": ["core.profile"],
                    },
                    {
                        "title": "Resumelar",
                        "icon": "description",
                        "link": "/admin/core/resume/",
                        "models": ["core.resume"],
                        "permission": "core.callbacks.is_not_tutor",
                    },
                ],
            },
            {
                "title": "Universtitet",
                "separator": True,
                "permission": "core.callbacks.is_not_tutor",
                "items": [
                    {
                        "title": "Fakultetlar",
                        "icon": "account_balance",
                        "link": "/admin/core/faculty/",
                        "models": ["core.faculty"],
                        "permission": "core.callbacks.is_not_tutor",
                    },
                    {
                        "title": "Yo'nalishlar",
                        "icon": "school",
                        "link": "/admin/core/major/",
                        "models": ["core.major"],
                        "permission": "core.callbacks.is_not_tutor",
                    },
                    {
                        "title": "Grant kvotalari",
                        "icon": "pie_chart",
                        "link": "/admin/core/grantquota/",
                        "models": ["core.grantquota"],
                        "permission": "core.callbacks.is_not_tutor",
                    },
                ],
            },
            {
                "title": "Ma'lumotlar",
                "separator": True,
                "permission": "core.callbacks.is_not_tutor",
                "items": [
                    {
                        "title": "E'lonlar",
                        "icon": "campaign",
                        "link": "/admin/core/announcement/",
                        "models": ["core.announcement"],
                        "permission": "core.callbacks.is_not_tutor",
                    },
                    {
                        "title": "Xabarlar",
                        "icon": "mail",
                        "link": "/admin/core/message/",
                        "models": ["core.message"],
                        "permission": "core.callbacks.is_not_tutor",
                    },
                ],
            },
        ],
    },
}
